import "./ContactsList.css";
import ContactItem from "./ContactItem";
import { useQuery } from "@tanstack/react-query";
import Card from "../../UI/Card";
import { useState, useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { getRandomName, getRandomCompany, getRandomJobTitle } from "./helpers";

const ContactsList = () => {
  const dispatch = useDispatch();
  const baseURL = useSelector((state) => state.baseURL);
  const contacts = useSelector((state) => state.contacts);
  const filterQuery = useSelector((state) => state.filterQuery);
  const nothingSelected = Object.values(filterQuery).every(
    (item) => item === 0
  );

  const [filterURL, setFilterURL] = useState("");
  useEffect(() => {
    if (nothingSelected) {
      setFilterURL(baseURL + "getFilteredLabels/?pc=0&hc=0&ec=0&rc=0");
    } else {
      setFilterURL(
        `${baseURL}getFilteredLabels/?pc=${filterQuery.item0}&hc=${filterQuery.item1}&ec=${filterQuery.item2}&rc=${filterQuery.item3}`
      );
    }
  }, [filterURL, nothingSelected, filterQuery, baseURL]);

  async function fetchContacts(filterURL) {
    try {
      const response = await fetch(filterURL);
      const contactsData = await response.json();

      dispatch({
        type: "setContacts",
        displayedContacts: contactsData,
      });
    } catch (error) {
      console.log(error);
    }
  }

  useEffect(() => {
    fetchContacts(filterURL);
  }, [filterURL]);

  let contactsEdited = contacts.map((contact) => ({
    prefix: "Mr",
    // firstName: getRandomName(),
    // middleName: getRandomName(),
    firstName: "Ahmed",
    middleName: "Ali",
    lastName: getRandomName(),
    title: getRandomJobTitle(),
    company: getRandomCompany(),
    type: "Client",

    ...contact,
  }));

  const contactsItems = contactsEdited.map((contact) => (
    <ContactItem
      key={contact.id}
      {...contact}
      // customerID={contact.customerID}
      // firstName={contact.firstName}
      // middleName={contact.middleName}
      // title={contact.title}
      // company={contact.company}
      // type={contact.type}
      // leadScore={contact.leadScore}
      // prefix={contact.prefix}
      // recency={contact.recency}
      // monetary={contact.monetary}
      // label={contact.label}
      // frequency={contact.frequency}
    />
  ));

  return (
    <Card className="contacts-list">
      {!(contactsItems.length > 0) && (
        <div className="message">No Contacts Found !</div>
      )}
      {contactsItems.length > 0 && contactsItems}
    </Card>
  );
};
export default ContactsList;

// const [contacts, setContacts] = useState([
//   {
//     id: 1,
//     customerID: "12347.00",
//     recency: 30,
//     frequency: 6,
//     monetary: "4085.18",
//     label: 0,
//     updated: null,
//     created: null,
//     prefix: "Mr",
//     firstName: "Osama",
//     middleName: "El-Sayed",
//     title: "Front-End Developer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 80,
//   },
//   {
//     id: 2,
//     customerID: "12348.00",
//     recency: 66,
//     frequency: 4,
//     monetary: "1437.24",
//     label: 0,
//     updated: null,
//     created: null,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ali",
//     title: "Junior Front-end Developer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 3,
//     customerID: "12349.00",
//     recency: 9,
//     frequency: 1,
//     monetary: "1457.55",
//     label: 0,
//     updated: null,
//     created: null,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 4,
//     customerID: "12350.00",
//     recency: 301,
//     frequency: 1,
//     monetary: "294.40",
//     label: 1,
//     updated: null,
//     created: null,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 5,
//     customerID: "12352.00",
//     recency: 27,
//     frequency: 8,
//     monetary: "1265.41",
//     label: 0,
//     updated: null,
//     created: null,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Client",
//     leadScore: 96,
//   },
//   {
//     id: 6,
//     customerID: "12353.00",
//     recency: 195,
//     frequency: 1,
//     monetary: "89.00",
//     label: 1,
//     updated: null,
//     created: null,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Client",
//     leadScore: 96,
//   },
//   {
//     id: 7,
//     customerID: "12354.00",
//     recency: 223,
//     frequency: 1,
//     monetary: "1079.40",
//     label: 1,
//     updated: null,
//     created: null,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Client",
//     leadScore: 96,
//   },
//   {
//     id: 8,
//     customerID: "12355.00",
//     recency: 205,
//     frequency: 1,
//     monetary: "459.40",
//     label: 1,
//     updated: null,
//     created: null,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Client",
//     leadScore: 96,
//   },
//   {
//     id: 9,
//     customerID: "12356.00",
//     recency: 13,
//     frequency: 3,
//     monetary: "2487.43",
//     label: 0,
//     updated: null,
//     created: null,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Client",
//     leadScore: 96,
//   },
//   {
//     id: 10,
//     customerID: "12357.00",
//     recency: 24,
//     frequency: 1,
//     monetary: "6207.67",
//     label: 0,
//     updated: null,
//     created: null,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Client",
//     leadScore: 96,
//   },
//   {
//     id: 11,
//     customerID: "12358.00",
//     recency: 141,
//     frequency: 1,
//     monetary: "404.86",
//     label: 1,
//     updated: null,
//     created: null,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Client",
//     leadScore: 96,
//   },
//   {
//     id: 12,
//     customerID: "12359.00",
//     recency: 48,
//     frequency: 5,
//     monetary: "6336.78",
//     label: 0,
//     updated: null,
//     created: null,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Client",
//     leadScore: 96,
//   },
//   {
//     id: 13,
//     customerID: "12360.00",
//     recency: 43,
//     frequency: 3,
//     monetary: "2302.06",
//     label: 0,
//     updated: null,
//     created: null,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Client",
//     leadScore: 96,
//   },
//   {
//     id: 14,
//     customerID: "12361.00",
//     recency: 278,
//     frequency: 1,
//     monetary: "174.90",
//     label: 1,
//     updated: null,
//     created: null,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Client",
//     leadScore: 96,
//   },
//   {
//     id: 15,
//     customerID: "12362.00",
//     recency: 2,
//     frequency: 12,
//     monetary: "4190.54",
//     label: 0,
//     updated: null,
//     created: null,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Client",
//     leadScore: 96,
//   },
//   {
//     id: 16,
//     customerID: "12363.00",
//     recency: 100,
//     frequency: 2,
//     monetary: "552.00",
//     label: 0,
//     updated: null,
//     created: null,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Client",
//     leadScore: 96,
//   },
//   {
//     id: 17,
//     customerID: "12364.00",
//     recency: 31,
//     frequency: 3,
//     monetary: "912.78",
//     label: 0,
//     updated: null,
//     created: null,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Client",
//     leadScore: 96,
//   },
//   {
//     id: 18,
//     customerID: "12365.00",
//     recency: 282,
//     frequency: 1,
//     monetary: "320.69",
//     label: 1,
//     updated: null,
//     created: null,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Client",
//     leadScore: 96,
//   },
//   {
//     id: 19,
//     customerID: "12370.00",
//     recency: 42,
//     frequency: 4,
//     monetary: "3425.69",
//     label: 0,
//     updated: null,
//     created: null,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 20,
//     customerID: "12371.00",
//     recency: 50,
//     frequency: 1,
//     monetary: "1527.96",
//     label: 0,
//     updated: null,
//     created: null,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },

//   {
//     id: 21,
//     customerID: "12372.00",
//     recency: 62,
//     frequency: 3,
//     monetary: "1196.04",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 22,
//     customerID: "12373.00",
//     recency: 302,
//     frequency: 1,
//     monetary: "324.60",
//     label: 1,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 23,
//     customerID: "12374.00",
//     recency: 16,
//     frequency: 1,
//     monetary: "622.93",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 24,
//     customerID: "12375.00",
//     recency: 1,
//     frequency: 2,
//     monetary: "377.50",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 25,
//     customerID: "12377.00",
//     recency: 306,
//     frequency: 2,
//     monetary: "1548.12",
//     label: 1,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 26,
//     customerID: "12378.00",
//     recency: 120,
//     frequency: 1,
//     monetary: "4008.62",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 27,
//     customerID: "12379.00",
//     recency: 72,
//     frequency: 3,
//     monetary: "775.29",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 28,
//     customerID: "12380.00",
//     recency: 12,
//     frequency: 5,
//     monetary: "2423.56",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 29,
//     customerID: "12381.00",
//     recency: 24,
//     frequency: 3,
//     monetary: "1326.45",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 30,
//     customerID: "12383.00",
//     recency: 175,
//     frequency: 6,
//     monetary: "1617.31",
//     label: 1,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 31,
//     customerID: "12384.00",
//     recency: 19,
//     frequency: 3,
//     monetary: "406.16",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 32,
//     customerID: "12386.00",
//     recency: 328,
//     frequency: 2,
//     monetary: "401.90",
//     label: 1,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 33,
//     customerID: "12388.00",
//     recency: 6,
//     frequency: 6,
//     monetary: "2780.66",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 34,
//     customerID: "12390.00",
//     recency: 70,
//     frequency: 1,
//     monetary: "504.84",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 35,
//     customerID: "12391.00",
//     recency: 12,
//     frequency: 1,
//     monetary: "460.89",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 36,
//     customerID: "12393.00",
//     recency: 63,
//     frequency: 4,
//     monetary: "1582.60",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 37,
//     customerID: "12394.00",
//     recency: 54,
//     frequency: 2,
//     monetary: "1080.48",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 38,
//     customerID: "12395.00",
//     recency: 6,
//     frequency: 15,
//     monetary: "2662.28",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 39,
//     customerID: "12397.00",
//     recency: 26,
//     frequency: 2,
//     monetary: "2214.90",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 40,
//     customerID: "12398.00",
//     recency: 36,
//     frequency: 1,
//     monetary: "1435.66",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 41,
//     customerID: "12399.00",
//     recency: 110,
//     frequency: 4,
//     monetary: "1033.65",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 42,
//     customerID: "12401.00",
//     recency: 294,
//     frequency: 1,
//     monetary: "69.30",
//     label: 1,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 43,
//     customerID: "12402.00",
//     recency: 314,
//     frequency: 1,
//     monetary: "195.60",
//     label: 1,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 44,
//     customerID: "12403.00",
//     recency: 40,
//     frequency: 1,
//     monetary: "391.70",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 45,
//     customerID: "12405.00",
//     recency: 139,
//     frequency: 1,
//     monetary: "1390.39",
//     label: 1,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 46,
//     customerID: "12406.00",
//     recency: 13,
//     frequency: 3,
//     monetary: "3280.75",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 47,
//     customerID: "12407.00",
//     recency: 40,
//     frequency: 5,
//     monetary: "1507.12",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 48,
//     customerID: "12408.00",
//     recency: 23,
//     frequency: 8,
//     monetary: "2587.57",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 49,
//     customerID: "12409.00",
//     recency: 69,
//     frequency: 7,
//     monetary: "11056.93",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 50,
//     customerID: "12410.00",
//     recency: 292,
//     frequency: 3,
//     monetary: "521.08",
//     label: 1,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 51,
//     customerID: "12412.00",
//     recency: 65,
//     frequency: 3,
//     monetary: "1142.88",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 52,
//     customerID: "12413.00",
//     recency: 57,
//     frequency: 4,
//     monetary: "676.15",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 53,
//     customerID: "12414.00",
//     recency: 208,
//     frequency: 3,
//     monetary: "442.41",
//     label: 1,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 54,
//     customerID: "12415.00",
//     recency: 15,
//     frequency: 21,
//     monetary: "101452.26",
//     label: 2,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 55,
//     customerID: "12417.00",
//     recency: 20,
//     frequency: 11,
//     monetary: "2831.07",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 56,
//     customerID: "12418.00",
//     recency: 103,
//     frequency: 1,
//     monetary: "668.58",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 57,
//     customerID: "12420.00",
//     recency: 54,
//     frequency: 1,
//     monetary: "600.39",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 58,
//     customerID: "12421.00",
//     recency: 6,
//     frequency: 4,
//     monetary: "639.04",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 59,
//     customerID: "12422.00",
//     recency: 86,
//     frequency: 3,
//     monetary: "683.56",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 60,
//     customerID: "12423.00",
//     recency: 89,
//     frequency: 8,
//     monetary: "1430.47",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 61,
//     customerID: "12424.00",
//     recency: 153,
//     frequency: 2,
//     monetary: "1760.96",
//     label: 1,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 62,
//     customerID: "12425.00",
//     recency: 69,
//     frequency: 1,
//     monetary: "777.20",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 63,
//     customerID: "12426.00",
//     recency: 185,
//     frequency: 1,
//     monetary: "510.73",
//     label: 1,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 64,
//     customerID: "12427.00",
//     recency: 2,
//     frequency: 5,
//     monetary: "582.37",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 65,
//     customerID: "12428.00",
//     recency: 16,
//     frequency: 11,
//     monetary: "6366.00",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 66,
//     customerID: "12429.00",
//     recency: 0,
//     frequency: 4,
//     monetary: "3388.40",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 67,
//     customerID: "12430.00",
//     recency: 34,
//     frequency: 1,
//     monetary: "216.40",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 68,
//     customerID: "12431.00",
//     recency: 51,
//     frequency: 17,
//     monetary: "5709.95",
//     label: 3,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 69,
//     customerID: "12432.00",
//     recency: 33,
//     frequency: 4,
//     monetary: "4359.32",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 70,
//     customerID: "12433.00",
//     recency: 0,
//     frequency: 5,
//     monetary: "10737.18",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 71,
//     customerID: "12434.00",
//     recency: 75,
//     frequency: 4,
//     monetary: "765.19",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 72,
//     customerID: "12435.00",
//     recency: 70,
//     frequency: 2,
//     monetary: "7829.89",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 73,
//     customerID: "12436.00",
//     recency: 90,
//     frequency: 1,
//     monetary: "429.01",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 74,
//     customerID: "12437.00",
//     recency: 0,
//     frequency: 18,
//     monetary: "4280.76",
//     label: 3,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 75,
//     customerID: "12438.00",
//     recency: 5,
//     frequency: 2,
//     monetary: "2466.85",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 76,
//     customerID: "12441.00",
//     recency: 357,
//     frequency: 1,
//     monetary: "155.55",
//     label: 1,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 77,
//     customerID: "12444.00",
//     recency: 12,
//     frequency: 5,
//     monetary: "4085.46",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 78,
//     customerID: "12445.00",
//     recency: 13,
//     frequency: 1,
//     monetary: "77.40",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 79,
//     customerID: "12446.00",
//     recency: 48,
//     frequency: 1,
//     monetary: "1002.31",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 80,
//     customerID: "12447.00",
//     recency: 234,
//     frequency: 1,
//     monetary: "431.49",
//     label: 1,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 81,
//     customerID: "12448.00",
//     recency: 35,
//     frequency: 1,
//     monetary: "365.45",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 82,
//     customerID: "12449.00",
//     recency: 13,
//     frequency: 4,
//     monetary: "3596.29",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 83,
//     customerID: "12450.00",
//     recency: 147,
//     frequency: 2,
//     monetary: "197.88",
//     label: 1,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 84,
//     customerID: "12451.00",
//     recency: 1,
//     frequency: 6,
//     monetary: "8893.52",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 85,
//     customerID: "12452.00",
//     recency: 7,
//     frequency: 1,
//     monetary: "348.57",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 86,
//     customerID: "12453.00",
//     recency: 125,
//     frequency: 1,
//     monetary: "707.09",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 87,
//     customerID: "12454.00",
//     recency: 44,
//     frequency: 2,
//     monetary: "0.00",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 88,
//     customerID: "12455.00",
//     recency: 64,
//     frequency: 5,
//     monetary: "2339.86",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 89,
//     customerID: "12456.00",
//     recency: 35,
//     frequency: 4,
//     monetary: "2553.89",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 90,
//     customerID: "12457.00",
//     recency: 49,
//     frequency: 11,
//     monetary: "1597.78",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 91,
//     customerID: "12458.00",
//     recency: 62,
//     frequency: 2,
//     monetary: "787.40",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 92,
//     customerID: "12461.00",
//     recency: 145,
//     frequency: 1,
//     monetary: "626.88",
//     label: 1,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 93,
//     customerID: "12462.00",
//     recency: 9,
//     frequency: 3,
//     monetary: "916.79",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 94,
//     customerID: "12463.00",
//     recency: 37,
//     frequency: 6,
//     monetary: "1165.63",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 95,
//     customerID: "12464.00",
//     recency: 1,
//     frequency: 8,
//     monetary: "957.05",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 96,
//     customerID: "12465.00",
//     recency: 8,
//     frequency: 2,
//     monetary: "682.19",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 97,
//     customerID: "12468.00",
//     recency: 134,
//     frequency: 3,
//     monetary: "652.04",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 98,
//     customerID: "12471.00",
//     recency: 1,
//     frequency: 44,
//     monetary: "13484.41",
//     label: 3,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 99,
//     customerID: "12472.00",
//     recency: 21,
//     frequency: 13,
//     monetary: "5725.48",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
//   {
//     id: 100,
//     customerID: "12473.00",
//     recency: 44,
//     frequency: 4,
//     monetary: "2555.77",
//     label: 0,
//     prefix: "Mr",
//     firstName: "Ahmed",
//     middleName: "Ashraf",
//     title: "Senior Machine Learning Engineer",
//     company: "Amazon",
//     type: "Lead",
//     leadScore: 96,
//   },
// ]);
